version: '3.6'

networks:
  default:
    name: dapper_network

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /opt/mongo/db:/data/db
      - /opt/mongo/dump:/data/dump
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 12
  dapper:
    image: dapper:latest
    container_name: dapper
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - 389:389
       - 636:636
       - 1812:1812
       - 1389:1389
    environment:
      - DAPPER_MONGO_URL=mongodb://mongo:27017/dapper
    depends_on:
      - mongo
